version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    image: aaa/web
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: .docker/app-prod.docker
    image: aaa/app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
