version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    image: ecomailcz/web
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: .docker/app-dev.docker
    image: ecomailcz/app
    volumes:
      - ./:/var/www
    links:
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
  worker:
    build:
      context: ./
      dockerfile: .docker/worker.docker
    image: ecomailcz/worker
    volumes:
      - ./:/var/www
    links:
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
  redis:
    image: redis:3.0
    ports:
      - "6379:6379"
