version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    image: aaa/web
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    image: aaa/app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
