version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    image: ecomailcz/web
    volumes:
      - ../:/home
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    image: ecomailcz/app
    volumes:
      - ../:/home
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
